# Generated by Django 2.2 on 2020-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('c1', models.CharField(default='', max_length=200)),
                ('c2', models.CharField(default='', max_length=200)),
                ('c3', models.CharField(default='', max_length=200)),
                ('c4', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='c1', max_length=200)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
    ]
